<a href="https://colab.research.google.com/github/JangSeungHyun/practice/blob/master/practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**git 초기 설정**



In [72]:
!git add practice.ipynb

In [73]:
!git commit -m "message"

[master d9f8103] message
 1 file changed, 1 insertion(+), 1 deletion(-)
 rewrite practice.ipynb (95%)


In [74]:
!git push -u origin master

Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


In [5]:
import torch
import numpy as np

In [9]:
x = torch.Tensor([[1,2], [3,4]])
print(x)
x = torch.from_numpy(np.array([[1,2],[3,4]]))

print(x)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1, 2],
        [3, 4]])


In [10]:
x = np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [19]:
x = torch.FloatTensor(2,2)
y = torch.FloatTensor(2, 2)
y.requires_grad_(True)

with torch.no_grad():
  z = (x + y + torch.FloatTensor(2, 2))

print(z)

tensor([[4.1073e-35, 0.0000e+00],
        [3.7835e-43, 1.1210e-43]])


In [23]:
def linear(x, W, b):
  y = torch.mm(x, W) + b
  return y

x = torch.FloatTensor(16, 10)
W = torch.FloatTensor(10, 5)
b = torch.FloatTensor(5)

y = linear(x, W, b)

print(y)

tensor([[1.4011e-35, 0.0000e+00, 1.1210e-43, 0.0000e+00, 1.4013e-45],
        [1.4011e-35, 0.0000e+00, 1.1210e-43, 0.0000e+00, 1.4013e-45],
        [1.4011e-35, 0.0000e+00, 1.1210e-43, 0.0000e+00, 1.4013e-45],
        [1.4011e-35, 0.0000e+00, 1.1210e-43, 0.0000e+00, 1.4013e-45],
        [1.4011e-35, 0.0000e+00, 1.1210e-43, 0.0000e+00, 1.4013e-45],
        [1.4011e-35, 0.0000e+00, 1.1210e-43, 0.0000e+00, 1.4013e-45],
        [1.4011e-35, 0.0000e+00, 1.1210e-43, 0.0000e+00, 1.4013e-45],
        [1.4011e-35, 0.0000e+00, 1.1210e-43, 0.0000e+00, 1.4013e-45],
        [1.4011e-35, 0.0000e+00, 1.1210e-43, 0.0000e+00, 1.4013e-45],
        [1.4011e-35, 0.0000e+00, 1.1210e-43, 0.0000e+00, 1.4013e-45],
        [1.4011e-35, 0.0000e+00, 1.1210e-43, 0.0000e+00, 1.4013e-45],
        [1.4011e-35, 0.0000e+00, 1.1210e-43, 0.0000e+00, 1.4013e-45],
        [1.4011e-35, 0.0000e+00, 1.1210e-43, 0.0000e+00, 1.4013e-45],
        [1.4011e-35, 0.0000e+00, 1.1210e-43, 0.0000e+00, 1.4013e-45],
        [1.4011e-35,

In [36]:
import torch.nn as nn
class MyLinear(nn.Module):

  def __init__(self, input_size, output_size):
    super(MyLinear, self).__init__()

    self.linear = nn.Linear(input_size, output_size)

  def forward(self, x):
    y = self.linear(x)

    return y

In [37]:
x = torch.FloatTensor(16, 10)
linear = MyLinear(10, 5)

y = linear(x)

In [38]:
print(linear)

MyLinear(
  (linear): Linear(in_features=10, out_features=5, bias=True)
)


In [42]:
objective = 100

x = torch.FloatTensor(16, 10)
linear = MyLinear(10, 5)
y = linear(x)
loss = (objective - y.sum())**2

loss.backward()